config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root to: "home#index"
    resources :users
    resources :animes
  end

  scope module: "animefront" do
    root to: "home#index"
    get "/following", to: "follow_animes#index"
    get "/favorites", to: "favorite_animes#index"

    resources :animes, only: %i[index show] do
      resources :follow_animes, only: %i[create destroy]
      resources :favorite_animes, only: %i[create destroy]
    end
  end
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < AdminController
    def index
      authorize User, :index?
      @users = User.all.order(
        created_at: :desc,
      ).page(params[:page]).per(15)

      @animes = Anime.all.order(
        created_at: :desc,
      ).page(params[:page]).per(15)

      @favorites = FavoriteAnime.all

      @following = FollowAnime.all
    end
  end
end

app/controllers/animefront/animes_controller.rb
module Animefront
  class AnimesController < ClientController
    def index
      authorize Anime, :index?
      @animes = Anime.all.order(
        created_at: :desc,
      ).page(params[:page]).per(5)
    end

    def show
      authorize Anime, :show?
      @anime = Anime.find(params[:id])
    end
  end
end

app/controllers/animefront/client_controller.rb
module Animefront
  class ClientController < ApplicationController
    layout "animefront/layouts/application"

    include Pundit::Authorization

    def policy_scope(scope)
      super([:animefront, scope])
    end

    def authorize(record, query = nil)
      super([:animefront, record], query)
    end
  end
end

app/controllers/animefront/favorite_animes_controller.rb
module Animefront
  class FavoriteAnimesController < ClientController
    before_action :authenticate_user!

    def index
      authorize FavoriteAnime, :index?
      @favorites = current_user.favorite_animes.order(
        created_at: :desc,
      ).page(params[:page]).per(5)
    end

    def create
      @favorite = current_user.favorite_animes.new(anime: Anime.find(params[:anime_id]))
      authorize @favorite, :create?

      if @favorite.save
        FollowFavorite.new(current_user, @favorite).follow_favorite

        redirect_to "/favorites"
      else
        flash.now[:notice] = "Unable to favorite this anime"
      end
    end

    def destroy
      @favorite = current_user.favorite_animes.find(params[:id])
      authorize @favorite, :destroy?

      if @favorite.destroy
        redirect_to "/favorites"
      else
        flash.now[:notice] = "Unable to unfavorite this anime"
      end
    end
  end
end

app/controllers/animefront/follow_animes_controller.rb
module Animefront
  class FollowAnimesController < ClientController
    before_action :authenticate_user!

    def index
      authorize FollowAnime, :index?
      @following_animes = current_user.follow_animes.order(
        created_at: :desc,
      ).page(params[:page]).per(5)
    end

    def create
      @follow_anime = current_user.follow_animes.new(anime: Anime.find(params[:anime_id]))
      authorize @follow_anime, :create?

      if @follow_anime.save
        redirect_to "/following"
      else
        flash.now[:notice] = "Unable to follow this anime"
      end
    end

    def destroy
      @following_anime = current_user.follow_animes.find(params[:id])
      authorize @following_anime, :destroy?

      UnfollowFavorite.new(current_user, @following_anime).unfollow_favorite
      if @following_anime.destroy
        redirect_to "/following"
      else
        flash.now[:notice] = "Unable to unfollow this anime"
      end
    end
  end
end

app/controllers/animefront/home_controller.rb
module Animefront
  class HomeController < ClientController
    def index
      @animes = Anime.all.sample(6)
      @favorites = current_user.favorite_animes if current_user
      @following = current_user.follow_animes if current_user
    end
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/animefront/animes_helper.rb
module Animefront::AnimesHelper
end

app/helpers/animefront/client_helper.rb
module Animefront::ClientHelper
end

app/helpers/animefront/favorite_animes_helper.rb
module Animefront::FavoriteAnimesHelper
end

app/helpers/animefront/follow_animes_helper.rb
module Animefront::FollowAnimesHelper
end

app/helpers/animefront/home_helper.rb
module Animefront::HomeHelper
end

app/views/animefront/home/_anime_card.html.erb
<div class="card">
  <div class="card-image">  
    <figure class="image is-4by3">
      <a href="<%= anime_path(anime.id) %>"><%= image_tag anime.cover %>
    </figure>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-content">
        <p class="title is-4"><%= anime.name %></p>
        <% if current_user %>
          <div class="field is-grouped is-grouped-centered">
            <p class="control">
              <% if current_user.favorite_animes.find_by(anime: anime) %>
                <%= link_to icon("fas fa-2x", "star", class: "has-text-warning"), anime_favorite_anime_path(anime.id, current_user.favorite_animes.find_by(anime: anime)), method: :delete %>
              <% else %>
                <%= link_to icon("far fa-2x", "star", class: "has-text-warning"), anime_favorite_animes_path(anime.id), method: :post %>
              <% end %>
            </p>
            <p class="control">
              <% if current_user.follow_animes.find_by(anime: anime) %>
                <%= link_to icon("fas fa-2x", "thumbs-up", class: "has-text-info "), anime_follow_anime_path(anime.id, current_user.follow_animes.find_by(anime: anime)), method: :delete %>
              <% else %>
                <%= link_to icon("far fa-2x", "thumbs-up", class: "has-text-info "), anime_follow_animes_path(anime.id), method: :post %>
              <% end %>
            </p>
          </div>
        <% end %>          
      </div>
    </div>
  </div>
</div>

app/views/animefront/home/_authenticated_index.html.erb
<div class="box">
  <div class="columns">
    <div class="column is-half">
      <h1 class="title">Seus Favoritos:</h1>
      <%= render "favorites_table" %>
    </div>
    <div class="column is-half">
      <h1 class="title">Seus Animes seguidos:</h1>
      <%= render "following_table" %>
    </div>
  </div>
</div>
<hr>
<h1 class="title">Mais animes</h1>
<div class="columns">
  <% @animes.each do |anime| %>
    <div class="column">
      <%= render "anime_card", anime: anime %>
    </div>
  <% end %>
</div>

app/views/animefront/home/_favorites_table.html.erb
<div class="table-container">
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th class="has-text-centered">Cover</th>
        <th class="has-text-centered">Nome</th>
        <th class="has-text-centered">Status</th>
        <th class="has-text-centered">Release Date</th>
        <th class="has-text-centered">Finish Date</th>
      </tr>
    </thead>

    <tbody>
      <% @favorites.each do |favorite| %>
        <tr>
          <td class="has-text-centered"> <a href="<%= anime_path(favorite.anime) %>"><%= image_tag favorite.anime.cover, size: "70x70" %></a></td>
          <td class="has-text-centered"><%= favorite.anime.name %></td>
          <td class="has-text-centered"><%= favorite.anime.status %></td>
          <td class="has-text-centered"><%= favorite.anime.release_date %></td>
          <td class="has-text-centered"><%= favorite.anime.finish_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<% if @favorites.blank? %>
  <p class="title is-4 has-text-info has-text-centered">Nenhum anime aqui :(</p>
<% end %>

app/views/animefront/home/_following_table.html.erb
<div class="table-container">
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th class="has-text-centered">Cover</th>
        <th class="has-text-centered">Nome</th>
        <th class="has-text-centered">Status</th>
        <th class="has-text-centered">Release Date</th>
        <th class="has-text-centered">Finish Date</th>
      </tr>
    </thead>

    <tbody>
      <% @following.each do |followed| %>
        <tr>
          <td class="has-text-centered"><a href="<%= anime_path(followed.anime) %>"><%= image_tag followed.anime.cover, size: "70x70" %></a></td>
          <td class="has-text-centered"><%= followed.anime.name %></td>
          <td class="has-text-centered"><%= followed.anime.status %></td>
          <td class="has-text-centered"><%= followed.anime.release_date %></td>
          <td class="has-text-centered"><%= followed.anime.finish_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<% if @following.blank? %>
  <p class="title is-4 has-text-info has-text-centered">Nenhum anime aqui :(</p>
<% end %>

app/views/animefront/home/_unauthenticated_index.html.erb
<div class="tile is-ancestor">
  <div class="tile is-vertical is-5">
    <div class="tile">
      <div class="tile is-parent is-vertical">
        <article class="tile is-child notification is-primary">
          <p class="title">Cadastre-se</p>
          <p class="subtitle">
            Diversos animes para você escolher
          </p>
        </article>
        <article class="tile is-child notification is-warning">
          <p class="title">Seguir ou Favoritar</p>
          <p class="subtitle">
            Você pode seguir ou favoritar os animes que quiser, e encontrar eles na parte de animes seguidos/favoritos
          </p>
        </article>
        <article class="tile is-child notification is-danger">
          <p class="title">Informações</p>
          <p class="subtitle">
            Estamos sempre atualizando informações sobre os animes, basta clicar e ver as descrições
          </p>
        </article>
      </div>
      <div class="tile is-parent">
        <article class="tile is-child notification is-info">
          <p class="title">Atualizado</p>
          <p class="subtitle">
            Sempre com os melhores animes
          </p>
          <figure class="image is-4by3">
            <img src="https://www.animeunited.com.br/oomtumtu/2021/09/kimetsu.jpg">
          </figure>
          <br>
          <figure class="image is-4by3">
            <img src="https://image.winudf.com/v2/image/Y29tLmZtMzYwLnRoZWJlc3RhbmltZXdhbGxwYXBlcl9zY3JlZW5fMF8xNTE1ODc5MzcwXzAxNQ/screen-0.jpg?fakeurl=1&type=.jpg">
          </figure>
          <br>
          <figure class="image is-4by3">
            <img src="https://wallpaperaccess.com/full/1665834.jpg">
          </figure>
          <br>
          <figure class="image is-4by3">
            <img src="https://wallpapermemory.com/uploads/564/goku-wallpaper-full-hd-462435.jpg">
          </figure>
        </article>
      </div>
    </div>
  </div>
  <div class="tile is-parent">
    <article class="tile is-child notification is-success">
      <div class="content">
        <p class="title">Veja alguns animes:</p>
        <div class="content">
          <% @animes.each_with_index do |anime, index| %>
            <% if index % 2 == 0 %>
              <div class="columns has-text-centered">
                <div class="column is-half">
                  <a href="/animes/<%= anime.id %>"><%= image_tag anime.cover %></a>
                  <p class="title"><%= anime.name %></p>
                </div>
            <% else %>
                <div class="column is-half">
                  <a href="/animes/<%= anime.id %>"><%= image_tag anime.cover %></a>
                  <p class="title"><%= anime.name %></p>
                </div>
              </div>
            <% end %>
          <% end %>
            </div>
          </div>
        </div>
      </div>
    </article>
  </div>
</div>

app/views/animefront/home/index.html.erb
<% if current_user %>
  <%= render "authenticated_index" %>
<% else %>
  <%= render "unauthenticated_index" %>
<% end %>