config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root to: "home#index"
    resources :users
    resources :animes
  end

  scope module: "animefront" do
    root to: "home#index"
    get "/following", to: "follow_animes#index"
    get "/favorites", to: "favorite_animes#index"

    resources :animes, only: %i[index show] do
      resources :follow_animes, only: %i[create destroy]
      resources :favorite_animes, only: %i[create destroy]
    end
  end
end

app/controllers/animefront/animes_controller.rb
module Animefront
  class AnimesController < ClientController
    def index
      authorize Anime, :index?
      @animes = Anime.all.order(
        created_at: :desc,
      ).page(params[:page]).per(5)
    end

    def show
      authorize Anime, :show?
      @anime = Anime.find(params[:id])
    end
  end
end

app/controllers/animefront/client_controller.rb
module Animefront
  class ClientController < ApplicationController
    layout "animefront/layouts/application"

    include Pundit::Authorization

    def policy_scope(scope)
      super([:animefront, scope])
    end

    def authorize(record, query = nil)
      super([:animefront, record], query)
    end
  end
end

app/controllers/animefront/favorite_animes_controller.rb
module Animefront
  class FavoriteAnimesController < ClientController
    before_action :authenticate_user!

    def index
      authorize FavoriteAnime, :index?
      @favorites = current_user.favorite_animes.order(
        created_at: :desc,
      ).page(params[:page]).per(5)
    end

    def create
      @favorite = current_user.favorite_animes.new(anime: Anime.find(params[:anime_id]))
      authorize @favorite, :create?

      if @favorite.save
        FollowFavorite.new(current_user, @favorite).follow_favorite

        redirect_to "/favorites"
      else
        flash.now[:notice] = "Unable to favorite this anime"
      end
    end

    def destroy
      @favorite = current_user.favorite_animes.find(params[:id])
      authorize @favorite, :destroy?

      if @favorite.destroy
        redirect_to "/favorites"
      else
        flash.now[:notice] = "Unable to unfavorite this anime"
      end
    end
  end
end

app/controllers/animefront/follow_animes_controller.rb
module Animefront
  class FollowAnimesController < ClientController
    before_action :authenticate_user!

    def index
      authorize FollowAnime, :index?
      @following_animes = current_user.follow_animes.order(
        created_at: :desc,
      ).page(params[:page]).per(5)
    end

    def create
      @follow_anime = current_user.follow_animes.new(anime: Anime.find(params[:anime_id]))
      authorize @follow_anime, :create?

      if @follow_anime.save
        redirect_to "/following"
      else
        flash.now[:notice] = "Unable to follow this anime"
      end
    end

    def destroy
      @following_anime = current_user.follow_animes.find(params[:id])
      authorize @following_anime, :destroy?

      UnfollowFavorite.new(current_user, @following_anime).unfollow_favorite
      if @following_anime.destroy
        redirect_to "/following"
      else
        flash.now[:notice] = "Unable to unfollow this anime"
      end
    end
  end
end

app/controllers/animefront/home_controller.rb
module Animefront
  class HomeController < ClientController
    def index
      @animes = Anime.all.sample(6)
      @favorites = current_user.favorite_animes if current_user
      @following = current_user.follow_animes if current_user
    end
  end
end

app/helpers/animefront/animes_helper.rb
module Animefront::AnimesHelper
end

app/helpers/animefront/client_helper.rb
module Animefront::ClientHelper
end

app/helpers/animefront/favorite_animes_helper.rb
module Animefront::FavoriteAnimesHelper
end

app/helpers/animefront/follow_animes_helper.rb
module Animefront::FollowAnimesHelper
end

app/helpers/animefront/home_helper.rb
module Animefront::HomeHelper
end

app/views/animefront/layouts/_client_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to icon("fas fa-2x", "home", "Home"), root_path, class: "navbar-item" %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Animes", animes_path, class: "navbar-item" %>

      <% if current_user %>
        <%= link_to "Favoritos", favorites_path, class: "navbar-item" %>
        <%= link_to "Seguidos", following_path, class: "navbar-item" %>
      <% end %>
    </div>

    <div class="navbar-end">
      <% if current_user %>
        <div class="navbar-item">
          <a class="button is-dark is-outlined is-static">
            Olá, <%= current_user.name %>
          </a>
        </div>
      <% end %>
      <div class="navbar-item">
        <div class="buttons">
          <% if current_user %>
            <% if current_user.admin? %>
              <%= link_to "Modo Admin", admin_root_path, class: "button is-info" %>
            <% end %>
            <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "button is-danger" %>
          <% else %>
            <%= link_to "Cadastre-se", new_user_registration_path, class: "button is-primary" %>
            <%= link_to "Entrar", new_user_session_path, class: "button is-light" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/animefront/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimeList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    <%= render "animefront/layouts/client_navbar" %>
    <div class="section">
      <%= yield %>
    </div>
  </body>
</html>