config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root to: "home#index"
    resources :users
    resources :animes
  end

  scope module: "animefront" do
    root to: "home#index"
    get "/following", to: "follow_animes#index"
    get "/favorites", to: "favorite_animes#index"

    resources :animes, only: %i[index show] do
      resources :follow_animes, only: %i[create destroy]
      resources :favorite_animes, only: %i[create destroy]
    end
  end
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_many :favorite_animes, dependent: :destroy
  has_many :users, through: :favorite_animes
  has_many :follow_animes, dependent: :destroy

  has_one_attached :cover
  has_rich_text :description

  validates :cover, presence: true
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
  validates :status, presence: true
  validates :release_date, presence: true, future_date: true
  validates :finish_date, future_date: true

  enum status: { complete: 0, in_progress: 1, stopped: 2 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite_anime.rb
class FavoriteAnime < ApplicationRecord
  belongs_to :user
  belongs_to :anime
end

app/models/follow_anime.rb
class FollowAnime < ApplicationRecord
  belongs_to :user
  belongs_to :anime
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorite_animes, dependent: :destroy
  has_many :animes, through: :favorite_animes
  has_many :follow_animes, dependent: :destroy

  validates :name, presence: true
  validates :profile, presence: true

  enum profile: { admin: 0, otaku: 1 }
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    layout "admin/layouts/application"

    include Pundit::Authorization
    after_action :verify_authorized

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    def policy_scope(scope)
      super([:admin, scope])
    end

    def authorize(record, query = nil)
      super([:admin, record], query)
    end

    private

    def user_not_authorized
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to(request.referrer || root_path)
    end
  end
end

app/controllers/admin/animes_controller.rb
module Admin
  class AnimesController < AdminController
    before_action :set_anime, only: %i[show edit update destroy]

    def index
      authorize Anime, :index?
      @animes = Anime.all.order(
        created_at: :desc,
      ).page(params[:page]).per(15)
    end

    def show
      authorize Anime, :show?
    end

    def new
      authorize Anime, :new?
      @anime = Anime.new
    end

    def edit
      authorize Anime, :edit?
    end

    def create
      authorize Anime, :create?

      @anime = Anime.new
      @anime.attributes = anime_params

      if @anime.save
        redirect_to admin_animes_path, notice: "Anime was successfully created."
        return
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      authorize Anime, :update?

      @anime.attributes = anime_params

      if @anime.save
        redirect_to admin_animes_path, notice: "Anime was successfully updated."
        return
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      authorize Anime, :destroy?

      @anime.destroy
      redirect_to admin_users_path, notice: "User was successfully destroyed."
    end

    private

    def set_anime
      @anime = Anime.find(params[:id])
    end

    def anime_params
      params.require(:anime).permit(:id, :name, :description, :status, :cover, :release_date, :finish_date)
    end
  end
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < AdminController
    def index
      authorize User, :index?
      @users = User.all.order(
        created_at: :desc,
      ).page(params[:page]).per(15)

      @animes = Anime.all.order(
        created_at: :desc,
      ).page(params[:page]).per(15)

      @favorites = FavoriteAnime.all

      @following = FollowAnime.all
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < AdminController
    before_action :set_user, only: %i[show edit update destroy]

    def index
      authorize User, :index?
      @users = User.all.order(
        created_at: :desc,
      ).page(params[:page]).per(15)
    end

    def show
      authorize User, :show?
      @favorites = @user.favorite_animes.order(
        created_at: :desc,
      ).page(params[:page]).per(15)

      @following = @user.follow_animes.order(
        created_at: :desc,
      ).page(params[:page]).per(15)
    end

    def new
      authorize User, :new?
      @user = User.new
    end

    def edit
      authorize User, :edit?
    end

    def create
      authorize User, :create?

      @user = User.new
      @user.attributes = user_params
      if @user.save
        redirect_to admin_users_path, notice: "User was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      authorize User, :update?

      @user.attributes = user_params

      if @user.save
        redirect_to admin_users_path, notice: "User was successfully updated."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      authorize User, :destroy?

      @user.destroy
      redirect_to admin_users_path, notice: "User was successfully destroyed."
    end

    private

    def user_params
      params.require(:user).permit(:id, :name, :email, :password, :password_confirmation, :profile)
    end

    def set_user
      @user = User.find(params[:id])
    end
  end
end

app/controllers/animefront/animes_controller.rb
module Animefront
  class AnimesController < ClientController
    def index
      authorize Anime, :index?
      @animes = Anime.all.order(
        created_at: :desc,
      ).page(params[:page]).per(5)
    end

    def show
      authorize Anime, :show?
      @anime = Anime.find(params[:id])
    end
  end
end

app/controllers/animefront/client_controller.rb
module Animefront
  class ClientController < ApplicationController
    layout "animefront/layouts/application"

    include Pundit::Authorization

    def policy_scope(scope)
      super([:animefront, scope])
    end

    def authorize(record, query = nil)
      super([:animefront, record], query)
    end
  end
end

app/controllers/animefront/home_controller.rb
module Animefront
  class HomeController < ClientController
    def index
      @animes = Anime.all.sample(6)
      @favorites = current_user.favorite_animes if current_user
      @following = current_user.follow_animes if current_user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/animes_helper.rb
module Admin::AnimesHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/animefront/animes_helper.rb
module Animefront::AnimesHelper
end

app/helpers/animefront/client_helper.rb
module Animefront::ClientHelper
end

app/helpers/animefront/favorite_animes_helper.rb
module Animefront::FavoriteAnimesHelper
end

app/helpers/animefront/follow_animes_helper.rb
module Animefront::FollowAnimesHelper
end

app/helpers/animefront/home_helper.rb
module Animefront::HomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/_animes_table.html.erb
<div class="table-container">
  <table class="table is-fullwidth">
    <thead>
      <tr>
        <th class="has-text-centered">Cover</th>
        <th class="has-text-centered">ID</th>
        <th class="has-text-centered">Nome</th>
        <th class="has-text-centered">Status</th>
        <th class="has-text-centered">Release Date</th>
        <th class="has-text-centered">Finish Date</th>
        <th colspan="3" class="has-text-centered">Ações</th>
      </tr>
    </thead>

    <tbody>
      <% animes.each do |anime| %>
        <tr>
          <td class="has-text-centered"><%= image_tag anime.cover, size: "70x70" %></td>
          <td class="has-text-centered"><%= anime.id %></td>
          <td class="has-text-centered"><%= anime.name %></td>
          <td class="has-text-centered"><%= anime.status %></td>
          <td class="has-text-centered"><%= anime.release_date %></td>
          <td class="has-text-centered"><%= anime.finish_date %></td>
          <td>
            <%= link_to icon("fas", "eye", "Ver |"), admin_anime_path(anime) %>
            <%= link_to icon("fas", "pen", "Editar |"), edit_admin_anime_path(anime) %>
            <%= link_to icon("fas", "trash-alt", "Deletar"), admin_anime_path(anime), method: :delete, data: { confirm: "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="pagination">
  <p class="title"><%= paginate animes %></p>
</div>

<% if animes.blank? %>
  <p class="title is-4 has-text-info has-text-centered">Nenhum anime aqui :(</p>
<% end %>

app/views/admin/users/_form.html.erb
<div class="columns">
  <div class="column is-half is-offset-one-quarter">
    <div class="card">
      <div class="card-header">
        <p class="card-header-title">Formulário de Usuário</p>
      </div>
      <div class="card-content">
        <%= form_with(model: user, url: url) do |form| %>
          <% if user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

              <ul>
                <% user.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= form.label :name, class: "label" %>
            <div class="control">
              <%= form.text_field :name, class: "input is-primary", placeholder: "Nome" %>
            </div>
          </div>

          <div class="field">
            <%= form.label :email, class: "label" %>
            <div class="control">
              <%= form.text_field :email, class: "input is-primary", placeholder: "Email" %>
            </div>
          </div>

          <div class="field">
            <%= form.label :profile, class: "label" %>
            <div class="select is-primary">
              <%= form.select :profile, User.profiles.keys.map { |w| [w.humanize, w] } %>
            </div>
          </div>

          <div class="field">
            <%= form.label :password, class: "label" %>
            <%= form.password_field :password, class: "input is-primary", placeholder: "Senha" %>
          </div>

          <div class="field is-grouped is-grouped-centered">
            <div class="control">
              <%= form.submit "Concluído", class: "button is-primary" %>
            </div>
            <div class="control">
              <%= link_to "Voltar", admin_users_path, class: "button is-warning" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<%= render "form", user: @user, url: admin_user_path %>

app/views/admin/users/index.html.erb
<div class="columns">
  <div class="column is-full">
    <nav class="level">
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Usuários</p>
          <p class="title"><%= @users.size %></p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Novo Usuário</p>
          <%= link_to icon("fas", "user"), new_admin_user_path, class: "button is-primary is-outlined" %>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Voltar</p>
          <%= link_to icon("fas", "arrow-left"), (:back || admin_root_path), class: "button is-primary is-outlined" %>
        </div>
      </div>
    </nav>
  </div>
</div>

<hr>

<div class="columns">
  <div class="column">
    <%= render "admin/home/users_table" %>
  </div>
</div>

app/views/admin/users/new.html.erb
<%= render "form", user: @user, url: admin_users_path %>

app/views/admin/users/show.html.erb
<div class="columns">
  <div class="column is-full">
    <nav class="level">
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Usuário</p>
          <p class="title is-5"><%= @user.name %></p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Editar</p>
          <%= link_to icon("fas", "pen"), edit_admin_user_path(@user), class: "button is-primary is-outlined" %>
        </div>
      </div>
      <% if @user.otaku? %>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">Excluir</p>
            <%= link_to icon("fas", "trash-alt"), admin_user_path(@user), method: :delete, data: { confirm: "Tem certeza?" }, class: "button is-danger is-outlined" %>
          </div>
        </div>
      <% end %>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Voltar</p>
          <%= link_to icon("fas", "arrow-left"), (:back || admin_root_path), class: "button is-primary is-outlined" %>
        </div>
      </div>
    </nav>
  </div>
</div>

<hr>

<div class="box">
  <div class="columns">
    <div class="column">
      <h1 class="title is-4">Nome</h1>
      <p class="subtitle"><%= @user.name %></p>
    </div>
    <div class="column">
      <h1 class="title is-4">Email</h1>
      <p class="subtitle"><%= @user.email %></p>
    </div>
  </div>
  <hr>
  <div class="columns">
    <div class="column">
      <h1 class="title is-4">Animes Favoritos</h1>
      <%= render "animes_table", animes: @favorites %>
    </div>
    <div class="column">
      <h1 class="title is-4">Animes Seguidos</h1>
      <%= render "animes_table", animes: @following %>
    </div>
  </div>
</div>