config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    root to: "home#index"
    resources :users
    resources :animes
  end

  scope module: "animefront" do
    root to: "home#index"
    get "/following", to: "follow_animes#index"
    get "/favorites", to: "favorite_animes#index"

    resources :animes, only: %i[index show] do
      resources :follow_animes, only: %i[create destroy]
      resources :favorite_animes, only: %i[create destroy]
    end
  end
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_many :favorite_animes, dependent: :destroy
  has_many :users, through: :favorite_animes
  has_many :follow_animes, dependent: :destroy

  has_one_attached :cover
  has_rich_text :description

  validates :cover, presence: true
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true
  validates :status, presence: true
  validates :release_date, presence: true, future_date: true
  validates :finish_date, future_date: true

  enum status: { complete: 0, in_progress: 1, stopped: 2 }
end

app/controllers/admin/animes_controller.rb
module Admin
  class AnimesController < AdminController
    before_action :set_anime, only: %i[show edit update destroy]

    def index
      authorize Anime, :index?
      @animes = Anime.all.order(
        created_at: :desc,
      ).page(params[:page]).per(15)
    end

    def show
      authorize Anime, :show?
    end

    def new
      authorize Anime, :new?
      @anime = Anime.new
    end

    def edit
      authorize Anime, :edit?
    end

    def create
      authorize Anime, :create?

      @anime = Anime.new
      @anime.attributes = anime_params

      if @anime.save
        redirect_to admin_animes_path, notice: "Anime was successfully created."
        return
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      authorize Anime, :update?

      @anime.attributes = anime_params

      if @anime.save
        redirect_to admin_animes_path, notice: "Anime was successfully updated."
        return
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      authorize Anime, :destroy?

      @anime.destroy
      redirect_to admin_users_path, notice: "User was successfully destroyed."
    end

    private

    def set_anime
      @anime = Anime.find(params[:id])
    end

    def anime_params
      params.require(:anime).permit(:id, :name, :description, :status, :cover, :release_date, :finish_date)
    end
  end
end

app/controllers/animefront/animes_controller.rb
module Animefront
  class AnimesController < ClientController
    def index
      authorize Anime, :index?
      @animes = Anime.all.order(
        created_at: :desc,
      ).page(params[:page]).per(5)
    end

    def show
      authorize Anime, :show?
      @anime = Anime.find(params[:id])
    end
  end
end

app/helpers/admin/animes_helper.rb
module Admin::AnimesHelper
end

app/helpers/animefront/animes_helper.rb
module Animefront::AnimesHelper
end

app/views/admin/animes/_form.html.erb
<div class="columns">
  <div class="column is-half is-offset-one-quarter">
    <div class="card">
      <div class="card-header">
        <p class="card-header-title">Formulário de Anime</p>
      </div>
      <div class="card-content">
        <%= form_with(model: anime, url: url) do |form| %>
          <% if anime.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(anime.errors.count, "error") %> prohibited this anime from being saved:</h2>

              <ul>
                <% anime.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= form.label :name, class: "label" %>
            <div class="control">
              <%= form.text_field :name, class: "input is-primary", placeholder: "Nome" %>
            </div>
          </div>

          <div class="field">
            <%= form.label :cover, class: "label" %>
            <div class="control">
              <%= form.file_field :cover, class: "input is-primary", placeholder: "Nome" %>
            </div>
          </div>

          <div class="field">
            <%= form.label :description, class: "label" %>
            <div class="control">
              <%= form.rich_text_area :description, placeholder: "Descrição" %>
            </div>
          </div>

          <div class="field">
            <%= form.label :status, class: "label" %>
            <div class="select is-primary">
              <%= form.select :status, Anime.statuses.keys.map { |w| [w.humanize, w] } %>
            </div>
          </div>

          <div class="columns">
            <div class="column is-3 is-offset-4">
              <div class="field">
                <%= form.label :release_date, class: "label" %>
                <%= form.date_field :release_date, class: "input is-primary" %>
              </div>
            </div>
            <div class="column is-3">
              <div class="field">
                <%= form.label :finish_date, class: "label" %>
                <%= form.date_field :finish_date, class: "input is-primary" %>
              </div>
            </div>
          </div>

          <div class="field is-grouped is-grouped-centered">
            <div class="control">
              <%= form.submit "Concluído", class: "button is-primary" %>
            </div>
            <div class="control">
              <%= link_to "Voltar", admin_animes_path, class: "button is-warning" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/animes/edit.html.erb
<%= render "form", anime: @anime, url: admin_anime_path %>

app/views/admin/animes/index.html.erb
<div class="columns">
  <div class="column is-full">
    <nav class="level">
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Animes</p>
          <p class="title"><%= @animes.size %></p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Novo Anime</p>
          <%= link_to icon("fas", "user"), new_admin_anime_path, class: "button is-primary is-outlined" %>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Voltar</p>
          <%= link_to icon("fas", "arrow-left"), (:back || admin_root_path), class: "button is-primary is-outlined" %>
        </div>
      </div>
    </nav>
  </div>
</div>

<hr>

<div class="columns">
  <div class="column">
    <%= render "admin/home/animes_table" %>
  </div>
</div>

app/views/admin/animes/new.html.erb
<%= render "form", anime: @anime, url: admin_animes_path %>

app/views/admin/animes/show.html.erb
<div class="columns">
  <div class="column is-full">
    <nav class="level">
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Anime</p>
          <p class="title is-5"><%= @anime.name %></p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Editar</p>
          <%= link_to icon("fas", "pen"), edit_admin_anime_path(@anime), class: "button is-primary is-outlined" %>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Excluir</p>
          <%= link_to icon("fas", "trash-alt"), admin_anime_path(@anime), method: :delete, data: { confirm: "Tem certeza?" }, class: "button is-danger is-outlined" %>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Voltar</p>
          <%= link_to icon("fas", "arrow-left"), (:back || admin_root_path), class: "button is-primary is-outlined" %>
        </div>
      </div>
    </nav>
  </div>
</div>

<hr>

<div class="box">
  <div class="columns">
    <div class="column is-half is-offset-one-quarter">
      <%= image_tag @anime.cover %>
    </div>
  </div>

  <div class="columns">
    <div class="column">
      <h1 class="title is-4">Nome</h1>
      <p class="subtitle"><%= @anime.name %></p>
    </div>
    <div class="column">
      <h1 class="title is-4">Status</h1>
      <p class="subtitle"><%= @anime.status %></p>
    </div>
    <div class="column">
      <h1 class="title is-4">Lançamento</h1>
      <p class="subtitle"><%= @anime.release_date %></p>
    </div>
    <% if @anime.finish_date %>
      <div class="column">
        <h1 class="title is-4">Finalizado</h1>
        <p class="subtitle"><%= @anime.finish_date %></p>
      </div>
    <% end %>
  </div>

  <hr>

  <div class="columns">
    <div class="column">
      <p><%= @anime.description %></p>
    </div>
  </div>
</div>